#!/bin/sh

# Check if there are any local dependencies in the package.json file
local_deps=$(grep -E "file:.*\..*" package.json)

# If local dependencies are found, exit with an error message
if [ "$local_deps" ]; then
  echo "ERROR: Local dependencies found in package.json:"
  echo "$local_deps"
  echo "Push blocked to prevent committing local dependencies."
  exit 1
fi

# Check if publishable key is set in App.tsx
# Get the length of the PUBLISHABLE_KEY constant
LENGTH=$(grep -o 'PUBLISHABLE_KEY = .*' App.tsx | cut -d'"' -f2 | wc -c | awk '{$1=$1-1}1')

if [ $LENGTH -eq 86 ]; then
  echo "ERROR: PUBLISHABLE_KEY is set"
  exit 1
fi

# If no local dependencies are found, allow the push to proceed
exit 0
